name: Update league json file
on: 
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create json file
        run: curl https://draft.premierleague.com/api/league/32589/details -o public/2023-24.json
      - name: Commit updated json file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated league json file"
          git push
