name: Update league json file
on: 
  schedule:
    - cron: '0 1,12,18 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FPL_UPDATOR_TOKEN }}
      - name: Create League Details file
        run: curl https://draft.premierleague.com/api/league/32589/details -o public/2023-24.json
      - name: Create Element Status file
        run: curl https://draft.premierleague.com/api/league/32589/element-status -o public/element-status-2023-24.json
      - name: Create Bootstrap file
        run: curl https://draft.premierleague.com/api/bootstrap-static -o public/bootstrap-static-2023-24.json
      - name: Create Transactions file
        run: curl https://draft.premierleague.com/api/draft/league/32589/transactions -o public/transactions-2023-24.json
      - name: Commit updated json file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated league json file"
          git push
