name: Update league json file
on: 
  schedule:
    - cron: '0 1,12,18 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update_json:
    runs-on: ubuntu-latest
    env:
      league_id: 7215
      season: 2024-25
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FPL_UPDATOR_TOKEN }}
      - name: Create League Details file
        run: curl https://draft.premierleague.com/api/league/$league_id/details -o public/$season.json
      - name: Create Element Status file
        run: curl https://draft.premierleague.com/api/league/$league_id/element-status -o public/element-status-$season.json
      - name: Create Bootstrap file
        run: curl https://draft.premierleague.com/api/bootstrap-static -o public/bootstrap-static-$season.json
      - name: Create Transactions file
        run: curl https://draft.premierleague.com/api/draft/league/$league_id/transactions -o public/transactions-$season.json
      - name: Commit updated json file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated league json file"
          git push
